options:
  volume-backend-name:
    type: string
    default:
    description: |
      Volume backend name for the backend. The default value is the
      application name in the Juju model.
  storage-protocol:
    type: string
    default:
    description: |
      SAN protocol to use. Choose between iSCSI or FC.
  san-ip:
    type: string
    default:
    description: |
      IP address of SAN controller.
  san-login:
    type: string
    default:
    description: |
      Username for SAN controller.
  san-password:
    type: string
    default:
    description: |
      Password for SAN controller. SSH key pair authentication is not
      supported by the charm at this moment.
  powerstore_ports:
    type: string
    default:
    description: |
      A comma-separated list of iSCSI or FC ports to be used. 
      Each port can be Unix-style glob expressions.
  driver-source:
    type: string
    default:
    description: |
      Optional configuration to support use of additional sources such as:
        - ppa:myteam/ppa
        - cloud:trusty-proposed/kilo
        - http://my.archive.com/ubuntu main
      The last option should be used in conjunction with the key configuration
      option.
  driver-key:
    type: string
    default:
    description: |
      Key ID to import to the apt keyring to support use with arbitary source
      configuration from outside of Launchpad archives or PPA's.
